name: Test background processes
on: push
env:
  NUNIT_CONSOLE_VERSION: 3.12.0
  NUGET_EXE: /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe
  NUNIT_CONSOLE: /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe
jobs:
  Test:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Nuget restore
        run: |
          mono ${{ env.NUGET_EXE }} restore App1/App1.sln &
          mono ${{ env.NUGET_EXE }} install NUnit.Console          
