name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - run: ls /Users/runner/Library/Android/sdk/tools
      - run: ls /Users/runner/Library/Android/sdk/tools/bin/sdkmanager
      - run: /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --list
      
      - run: yes | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses &
      
      - name: Download emu
        run: |
          cd /Users/runner/Library/Android/sdk/tools/bin
          ./sdkmanager 'system-images;android-28;google_apis;x86'
          echo "no" | ./avdmanager --verbose create avd --force --name "pixel_9.0" --device "pixel" --package "system-images;android-28;google_apis;x86" --tag "google_apis" --abi "x86"
          
      - name: list avd
        run: emulator -list-avds
        
      - name: list 2
        run: /Users/runner/Library/Android/sdk/tools/emulator -list-avds
