name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: list avd
        run: |
          echo "ANDROID_HOME=/Users/runner/android/sdk" >> $GITHUB_ENV
          emulator -list-avds
