name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: list avd
        run: |
          ls /Users/runner/Library/Android/sdk
          ls /Users/runner/Library/Android/sdk**
          
          
