name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - run: ls /Users/runner/Library/Android/sdk/tools
      - run: ls /Users/runner/Library/Android/sdk/tools/bin/sdkmanager
      - run: /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --list
      
      - name: List avd
        run: |
          /Users/runner/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-29" "build-tools;30.0.3" "add-ons;addon-google_apis-google-23"
          /Users/runner/Library/Android/sdk/tools/bin/sdkmanager 'system-images;android-29;google_apis;x86'
          /Users/runner/Library/Android/sdk/tools/bin/avdmanager create avd --force --name myTestDevice --abi google_apis/x86 --package 'system-images;android-29;google_apis;x86' --device "myTestDevice"
          /Users/runner/Library/Android/sdk/tools/bin/emulator -list-avds
