name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
          
      - name: Accept licenses
        run: yes | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses &
        
      - name: ls
        run: ls /Users/runner/Library/Android/sdk/tools
      
      - name: Download emu
        run: |
          cd /Users/runner/Library/Android/sdk/tools/bin
          ./sdkmanager 'system-images;android-25;google_apis;x86'
          echo "no" | ./avdmanager --verbose create avd --force --name "pixel_9.0" --device "pixel" --package "system-images;android-25;google_apis;x86" --tag "google_apis" --abi "x86"
          
      - name: list avd
        run: emulator -list-avds
        
      - name: list 2
        run: /Users/runner/Library/Android/sdk/tools/emulator -list-avds
        
      - name: what
        run: |
          ls $HOME/.android/avd
    

      - name: start emulator
        run: /Users/runner/Library/Android/sdk/emulator/emulator @pixel_9.0 & /Users/runner/Library/Android/sdk/tools/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
