name: Check
on: push
jobs: 
  Android:
    runs-on: ubuntu-18.04
    steps:
      - name: Accept licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses &
      
      - name: Download emu
        if: steps.emulator.outputs.cache-hit != 'true'
        run: |
          cd /usr/local/lib/android/sdk/tools/bin
          ./sdkmanager 'system-images;android-25;google_apis;x86'
          echo "no" | ./avdmanager --verbose create avd --force --name "pixel_9.0" --device "pixel" --package "system-images;android-25;google_apis;x86" --tag "google_apis" --abi "x86"
          
       
      - name: list 2
        run: | 
          /usr/local/lib/android/sdk/tools/emulator -list-avds
          echo "\n"
          ls /usr/local/lib/android/sdk/tools/
          echo "\n"
          ls /usr/local/lib/android/sdk/tools/**
   

      - name: start emulator
        run: /usr/local/lib/android/sdk/tools/emulator @pixel_9.0

        
        


