name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
    
      - name: Cache emulator
        uses: actions/cache@v2
        id: emulator
        with:
          path: |
            /Users/runner/.android/avd
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager
          key: ${{ runner.os }}-pixel_9.0-
          
      - name: Accept licenses
        if: steps.emulator.outputs.cache-hit != 'true'
        run: yes | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses &
      
      - name: Download emu
        if: steps.emulator.outputs.cache-hit != 'true'
        run: |
          cd /Users/runner/Library/Android/sdk/tools/bin
          ./sdkmanager 'system-images;android-25;google_apis;x86'
          echo "no" | ./avdmanager --verbose create avd --force --name "pixel_9.0" --device "pixel" --package "system-images;android-25;google_apis;x86" --tag "google_apis" --abi "x86"
          
      - name: list avd
        run: emulator -list-avds
        
      - name: list 2
        run: /Users/runner/Library/Android/sdk/tools/emulator -list-avds
        
      - name: what
        run: |
          ls $HOME/.android/avd
    
      - name: start emulator
        run: /Users/runner/Library/Android/sdk/emulator/emulator @pixel_9.0
        

        
        


