name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: list avd
        run: |
          ls /Users/runner/android/sdk
          ls /Users/runner/android/sdk/**
          
          
