name: Check
on: push
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - run: ls /Users/runner/Library/Android/sdk/tools
      - run: ls /Users/runner/Library/Android/sdk/tools/bin/sdkmanager
      - run: /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --list
      
      - name: List avd
        run: |
          /Users/runner/Library/Android/sdk/tools/bin/avdmanager create avd --force --name myTestDevice --abi google_apis/x86 --package 'system-images;android-29;google_apis;x86 ' --device "myTestDevice"
          /Users/runner/Library/Android/sdk/tools/bin/emulator -list-avds
