name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd App1
        nuget restore
        cd App1
        msbuild App1.Android/App1.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:AndroidBuildApplicationPackage=true
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd App1
        nuget restore
        cd App1
        msbuild App1.iOS/App1.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  Tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Unit test
      run: |
        cd App1
        dotnet test XUnitTestProject
