name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    strategy:
      matrix:
        java_version: [15]
    steps:
    - uses: actions/checkout@v1
    - name: Install android-home
      shell: bash
      run: |
        brew install --cask android-sdk
    - name: Check for ANDROID-HOME
      run: |
        echo $ANDROID_HOME
        
