name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    strategy:
      matrix:
        java_version: [15]
    steps:
    - uses: actions/checkout@v1
    - name: Install android-home
      shell: bash
      run: |
        brew install --cask xamarin-android
    - name: echo path
      run: |
        echo $PATH
    - name: users runner library android
      run: |
        ls /Users/runner/Library/Android/
    - name: users runner library android sdk
      run: |
        ls /Users/runner/Library/Android/sdk
    - name: users runner library android sdk tools
      run: |
        ls /Users/runner/Library/Android/sdk/tools
    - name: add bin to path
      run: |
          echo "/Users/runner/Library/Android/sdk/tools/bin" >> $GITHUB_PATH
          echo "/Users/runner/Library/Android/sdk/emulator" >> $GITHUB_PATH
          echo "/Users/runner/Library/Android/sdk/ndk/21.4.7075529" >> $GITHUB_PATH
    - name: print path
      run: |
        echo $PATH
    - name: sdkmanager
      run: |
        sdkmanager --install "platform-tools" "platforms;android-28"
        sdkmanager --install "system-images;android-28;google_apis;x86"
        sdkmanager --licenses
    - name: create adb
      run: |
        avdmanager create avd -n Android28 -k "system-images;android-28;google_apis;x86"
    - name: run emulator
      run: |
        emulator -avd Android28
    - name: list of devices
      run: |
        adb devices
      
      
