name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Check env variable
        run: |
          echo $ANDROID_HOME
      - name: Emulator setup
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
