name: CI on Push and Pull Request
on: [push, pull_request]
jobs: 
  Android:
    name: "Build and test on Android"
    env:
      Device: "iPhone 11 (14.3)"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      - run: ls /Applications | grep Xcode
      - run: xcrun simctl list
      - run: echo "NUGET_EXE=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe" >> $GITHUB_ENV
      - run: echo "NUNIT3-CONSOLE=/Library/Frameworks/Mono.framework/Versions//6.12.0/Commands/nunit3-console" >> $GITHUB_ENV
      - run: mono $NUGET_EXE install NUnit.Console
      - run: ls /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-28"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices
      
      - name: Restore Nuget Packages
        run: mono $NUGET_EXE restore App1/App1.sln
    
      - name: Build ios
        run: msbuild App1/App1/App1.iOS /p:Configuration=Release /p:Platform=iPhoneSimulator /t:Build
        
      - name: Check ios
        run: |
          ls App1/App1/App1.iOS/bin/iPhoneSimulator/Release
      - name: Build APK
        run: msbuild App1/App1/App1.Android/App1.Android.csproj -target:SignAndroidPackage /p:Configuration=Release
        
      - name: Build UI Test project
        run: msbuild App1/UItest/UItest.csproj /p:Configuration=Release
        
      - name: UITest iOS
        run: |
          open -a Simulator --args -CurrentDeviceUDID 58B9EF94-FF0C-4325-AED5-EC6D8B3744E2
          mono /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe App1/UItest/bin/Release/UItest.dll --where "test =~ iOS"
          
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: output
          path: App1/UItest/bin/Release/screenshots
        
      - name: UITest
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.6
        with:
            cmd: mono /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe App1/UItest/bin/Release/UItest.dll --where "test =~ Android"
            api: 28
            tag: default
            abi: x86   
            verbose: false
      
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: output
          path: App1/UItest/bin/Release/screenshots
        


