name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      # Download & install the Android SDK.
      - uses: malinskiy/action-android/install-sdk@release/0.1.1

      # Set up platform tools like adb.
      - run: sdkmanager platform-tools

      # Start ADB (and verify that pathing is working correctly).
      - run: adb devices

      # Verify $ANDROID_HOME is properly set for later Gradle commands.
      - run: echo $ANDROID_HOME
