name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    name: "Build and test on Android"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "NUGET_EXE=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe" >> $GITHUB_ENV
      - run: echo "NUNIT3-CONSOLE=/Library/Frameworks/Mono.framework/Versions//6.12.0/Commands/nunit3-console" >> $GITHUB_ENV
      - run: mono $NUGET_EXE install nunit-console
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-28"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices
      
      - name: Restore Nuget Packages
        run: mono $NUGET_EXE restore App1/App1.sln
      
        
      - name: Build APK
        run: |
          msbuild App1/App1/App1.Android/App1.Android.csproj -target:SignAndroidPackage /p:Configuration=Release
          msbuild App1/UItest/UItest.csproj /p:Configuration=Release
        

