name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:  
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
      - name: prufa
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        with:
          cmd: |
            sdkmanager platform-tools
            adb devices
            echo "WHAT IS UP"
            echo"HELLO"
            ls
          api: 25
          tag: default
          abi: x86
