name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - uses: malinskiy/action-android/install-sdk@release/0.1.1
    - run: sdkmanager platform-tools
    - run: adb devices
    - run: ls $ANDROID_HOME
    - run: ls /Users/runner/android-sdk/cmdline-tools
    - run: ls /Users/runner/android-sdk/licenses
    - run: ls /Users/runner/android-sdk/platform-tools
    - run: ls /Users/runner/android-sdk/sdk_home
    - run: brew install --cask xamarin-android
    - run: ls /Users/runner/android-sdk/cmdline-tools
    - run: ls /Users/runner/android-sdk/licenses
    - run: ls /Users/runner/android-sdk/platform-tools
    - run: ls /Users/runner/android-sdk/sdk_home
        

