name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - uses: malinskiy/action-android/install-sdk@release/0.1.1
    - name: Build Android
      run: |
        cd App1
        nuget restore
        cd App1
        msbuild App1.Android/App1.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:AndroidBuildApplicationPackage=True
        msbuild ../UITest/UITest.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
     
    - uses: malinskiy/action-android/install-sdk@release/0.1.1
    - run: sdkmanager platform-tools
    - run: adb devices
    - run: export value=$ANDROID_HOME
    - run: echo "{ANDROID_HOME}={value}" >> $GITHUB_ENV
        
    - name: Run UI test
      uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
      with:
        cmd: dotnet test MarvinMobile/UITest/bin/Release/UITest.dll
        api: 25
        tag: default
