name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    strategy:
      matrix:
        java_version: [15]
    steps:
    - uses: actions/checkout@v1
    - name: Check if exists
      run: |
        ls /Users/runner
    - name: Install JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Check again
      run: |
        cd /Users/runner/hostedtoolcache
        ls
        echo "Going in sdk"
        cd sdk
        echo "In sdk"
        ls
