name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:  
      - name: Install java
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Check env variable
      - run: |
          echo $ANDROID_HOME
