name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: prufa
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        with:
          cmd: |
            echo "WHAT IS UP"
            echo"HELLO"
            ls
          api: 25
          tag: default
          abi: x86
