name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: malinskiy/action-android/install-sdk@release/0.1.1
    - run: echo $ANDROID_HOME
    - run: sdkmanager platform-tools
    - run: sdkmanager "build-tools;25.0.2"
    - name: Build Android
      run: |
        cd App1
        nuget restore
        cd App1
        cat App1/AzureB2CSecrets.cs
        msbuild App1.Android/App1.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:AndroidBuildApplicationPackage=True
        msbuild ../UITest/UITest.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    
    - name: Run UI test
      uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
      with:
        cmd: dotnet test App1/UITest/bin/Release/UITest.dll
        api: 25
        tag: default
        abi: x86
