name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    name: "Build and test on Android"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "NUGET_EXE=/Users/runner/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe" >> $GITHUB_ENV
      - name: prufa
        run: |
          cd ~
          pwd
          ls
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-28"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices
      
      - run: echo $NUGET_EXE  
      
      - run: echo $GITHUB_WORKSPACE
      - name: Restore Nuget Packages
        run: mono $NUGET_EXE restore App1/App1.sln
