name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  Android:
    name: "Build and test on Android"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-28"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices
    
      - name: Setup Nuget
        uses: olegtarasov/download-nuget@v1
        
      - name: Restore Nuget Packages
        run: mono nuget restore App1/App1.sln
