name: CI
on: [push, pull_request]
jobs: 
  Android:
    name: "Build and test on iOS"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - run: echo "NUGET_EXE=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe" >> $GITHUB_ENV
      - run: echo "NUNIT3-CONSOLE=/Library/Frameworks/Mono.framework/Versions//6.12.0/Commands/nunit3-console" >> $GITHUB_ENV
      - run: mono $NUGET_EXE install NUnit.Console
      
      - name: Restore Nuget Packages
        run: mono $NUGET_EXE restore App1/App1.sln
    
      - name: Build ios
        run: msbuild App1/App1/App1.Android/App1.iOS.csproj -target:SignAndroidPackage /p:Configuration=Release
      - name: Build UI Test project
        run: msbuild App1/UItest/UItest.csproj /p:Configuration=Release
        
      - name: UITest iOS
        run: mono /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe App1/UItest/bin/Release/UItest.dll --where "test =~ iOS"
          
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: output
          path: App1/UItest/bin/Release/screenshots
