name: Improved
on: push
env:
  NUNIT_CONSOLE_VERSION: 3.12.0
  NUGET_EXE: /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe
  NUNIT_CONSOLE: /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
        with:
            ref: improved
            
            
      - name: Cache ./nuget/packages
        uses: actions/cache@v2
        with:
          path: | 
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/**/*.csproj') }}-${{ hashFiles('**/**/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
            
      - name: Nuget restore
        run: mono ${{ env.NUGET_EXE }} restore App1/App1.sln /:p:Configuration=Release
        
      - name: Cache NUnit.Console
        id: nunit-console
        uses: actions/cache@v2
        with:
          path: ./NUnit.ConsoleRunner.${{ env.NUNIT_CONSOLE_VERSION }}
          key: nunit-console-${{ env.NUNIT_CONSOLE_VERSION }}
          
      - name: Download NUnit-Console
        if: steps.nunit-console.outputs.cache-hit != 'true'
        run: mono ${{ env.NUGET_EXE }} install NUnit.Console -Version ${{ env.NUNIT_CONSOLE_VERSION }}
        
      - name: Build unit test
        run: msbuild App1/XUnitTestProject/XUnitTestProject.csproj
        
      - name: Run unit test
        run: mono ${{ env.NUNIT_CONSOLE }} App1/XUnitTestProject/bin/Release/XUnitTestProject.dll
