name: Improved
on: push
env:
  NUNIT_CONSOLE_VERSION: 3.12.0
  NUGET_EXE: /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe
  NUNIT_CONSOLE: /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe
jobs: 
  Android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
        with:
            ref: improved
        
          

 


            
      - name: Nuget restore
        run: nuget restore App1/App1.sln
        
      - name: Run test
        run: |
          dotnet build App1/XUnitTestProject/XUnitTestProject.csproj
          dotnet test App1/XUnitTestProject/XUnitTestProject.csproj
        
