name: Improved
on: push
env:
  NUNIT_CONSOLE_VERSION: 3.12.0
  NUGET_EXE: /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/nuget/nuget.exe
  NUNIT_CONSOLE: /Users/runner/work/my_mobile_app/my_mobile_app/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe
jobs: 
  Android:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
        with:
            ref: improved
            
            
      - name: Cache ./nuget/packages
        uses: actions/cache@v2
        with:
          path: | 
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/**/*.csproj') }}-${{ hashFiles('**/**/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
            
      - name: Nuget restore
        run: mono ${{ env.NUGET_EXE }} restore App1/App1.sln
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: |
          dotnet build App1/XUnitTestProject/XUnitTestProject.csproj
          dotnet test App1/XUnitTestProject/XUnitTestProject.csproj
        
